### ISSUE TITLE
Angular 2 support?

### ISSUE THREAD

**Issue by kodeine** [sanex3339/webpack-obfuscator#7]
Hello,
Can you please let me know how to use this JS obfuscator for [Angular2 Starter](https://github.com/AngularClass/angular2-webpack-starter)?

Thanks

**Comment by sanex3339** [comment]
You tried to follow readme? Any errors?

**Comment by kodeine** [comment]
@sanex3339 
no errors are printed, it just stucks for like a minute and webpack shows Ok. but compiling fails as webpack cant find html. 
Can you try at your end?

**Comment by sanex3339** [comment]
Later this day

**Comment by kodeine** [comment]
thank you

**Comment by sanex3339** [comment]
There a bunch of problems related to issue. One problem can be easyli fixed (plugin tried to obfuscate non `.js` formats). 
But other problem causing to runtime error. As i understand, this error happening as result of chunk splitting by webpack. It takes a time to analyze this error and find a way to fix it.

**Comment by kodeine** [comment]
Ahh, i'd be very thankful if you could find the soltuion. I really want to use obfuscation. Thanks for ur hard work btw

**Comment by sanex3339** [comment]
Ok, i found all problems, but now i need a time to analyze a way to fix it.

First problem related to plugin.
Plugin trying to obfuscate non-`.js` extensions. I can easily fix this by improving logic. I will do during weekend.

Second problem related to `javascript-obfuscator` itself.
Runtime error after obfuscation happens as result of two things: wrapping a class with `__decorate` method call with some strange variable declarations. And result of `uglifying` of this wrapped class.

Take a look at code before `uglifyjs`:

```
/***/ 409:
/***/ function(module, exports, __webpack_require__) {

"use strict";
"use strict";
var core_1 = __webpack_require__(0);
/*
 * Directive
 * XLarge is a simple directive to show how one is made
 */
var XLarge = (function () {
    function XLarge(element, renderer) {
        // simple DOM manipulation to set font size to x-large
        // `nativeElement` is the direct reference to the DOM element
        // element.nativeElement.style.fontSize = 'x-large';
        // for server/webworker support use the renderer
        renderer.setElementStyle(element.nativeElement, 'fontSize', 'x-large');
    }
    XLarge = __decorate([
        core_1.Directive({
            selector: '[x-large]' // using [ ] means selecting attributes
        }), 
        __metadata('design:paramtypes', [(typeof (_a = typeof core_1.ElementRef !== 'undefined' && core_1.ElementRef) === 'function' && _a) || Object, (typeof (_b = typeof core_1.Renderer !== 'undefined' && core_1.Renderer) === 'function' && _b) || Object])
    ], XLarge);
    return XLarge;
    var _a, _b;
}());
exports.XLarge = XLarge;


/***/ },
```

In the code you can see `var _a, _b;` line. Variables `_a` and `_b` is declared after `__decorate` method call and `return` statement but using before declaration.

Right now everything is ok, i have a test for this case:
Source code:
https://github.com/sanex3339/javascript-obfuscator/blob/master/src/node-obfuscators/VariableDeclarationObfuscator.ts#L58

Test:
https://github.com/sanex3339/javascript-obfuscator/blob/master/test/functional-tests/node-obfuscators/VariableDeclarationObfuscator.spec.ts#L57

But after minification with `uglifyjs` code becomes like that:
```
09: function (t, e, n) {
        "use strict";
        var o = n(0), a = function () {
            function XLarge(t, e) {
                e.setElementStyle(t.nativeElement, "fontSize", "x-large")
            }

            return XLarge = __decorate([o.Directive({selector: "[x-large]"}), __metadata("design:paramtypes", ["function" == typeof(t = "undefined" != typeof o.ElementRef && o.ElementRef) && t || Object, "function" == typeof(e = "undefined" != typeof o.Renderer && o.Renderer) && e || Object])], XLarge);
            var t, e
        }();
        e.XLarge = a
    },
```

You can see what names in first line with function parameters `09: function (t, e, n) {` and in line with variables `var t, e` are the same.

After obfuscation it breaks code, because obfuscator thinking what variables with names `t` and `e` inside `__decorate` method are function parameters, but they are `undefined` variables which was declared later inside `var t, e` line.

So, i looking for a solution.

**Comment by kodeine** [comment]
aaa makes sense. I kept wondering what could be causing this. But thank God you were able to find out the issue. Thanks for working on this to find a solution. hopefully it will help all angular users =) Best.

**Comment by sanex3339** [comment]
Looks like i understand how i can change algorythm to fix this, but this just a theory now.

**Comment by sanex3339** [comment]
Looks like i fixed runtime error. Need time to test it. Fix will be in `javascript-obfuscator@0.8.0-dev.1` version today/tomorrow + i should fix plugin. Minor patch for 0.7.* version will be later.

**Comment by sanex3339** [comment]
Runtime error fixes here:
https://github.com/sanex3339/javascript-obfuscator/commit/5469d4d3eda59d4f480aa19f36697c16e2e3c2d8
https://github.com/sanex3339/javascript-obfuscator/commit/3809f5445ad2634105e9c4b70a248efd8a27d6d8

**Comment by kodeine** [comment]
├── UNMET PEER DEPENDENCY webpack@2.1.0-beta.22
└── webpack-obfuscator@0.7.1 


and in config/webpack.dev.js i put 

```ts
// main 
const WebpackObfuscator = require('webpack-obfuscator');

// in plugins array.
    new WebpackObfuscator({
      rotateUnicodeArray: true
    }, ['excluded_bundle_name.js'])
```

its the same as before ? am i doing this right?

**Comment by sanex3339** [comment]
I didn't released tomorrow update to plugin, only for `javascript-obfuscator` with runtime error fix (0.7.2 version). Plugin will be updated today.

**Comment by kodeine** [comment]
@sanex3339 let me know when should i test it. also did i setup the obfuscator correctly? like i mentioned above?

**Comment by sanex3339** [comment]
`webpack-obfuscator@0.7.2` is out. Try it and say - your problem problem has been fixed or not?

**Comment by kodeine** [comment]
@sanex3339 works like a charm bro, thanks a lot for this update!

**Comment by sanex3339** [comment]
nice!

**Comment by kodeine** [comment]
@sanex3339 is it possible to just encrypt a single Class file that doing a whole project?
For example in this [repo](https://github.com/qdouble/angular-webpack2-starter) i just want encrypt a single class, how would i define that in webpack config? Can you please help.

**Comment by sanex3339** [comment]
Hi. This is plugin, so it works with output bundle files. In your case you can try to make this file as separate chunk with https://webpack.github.io/docs/list-of-plugins.html#commonschunkplugin and exclude every bundle/chunk except this one.

**Comment by molimpio** [comment]
https://ourcodeworld.com/articles/read/607/how-to-obfuscate-javascript-code-with-node-js
